# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7289d92786346dd3df4181c46ab25ac1e1c3031371a0f0a6d34910f64a38d8e392672d8ebdad436d75f587903f8ffa9323145ba3ca819bbf3621fc5047fc93e

test:
  secret_key_base: 6f41589b407b32c66688e8d7225906889303171b22217dd2db234f9f0ea8a03c2aa113570193057ec5033d5d2c10b7188cf0d2b7829d0a6d3d9edbca09442305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
